name: tekken8_framedata
description: tk8 framedata.
publish_to: 'none'

version: 7.0.0+78

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  shared_preferences: ^2.2.2
  string_validator: ^1.0.2
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  deepcopy: ^1.1.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_mobile_ads: ^4.0.0
  sticky_headers: ^0.3.0+2
  linked_scroll_controller: ^0.2.0
  restart_app: ^1.2.1
  url_launcher: ^6.2.5
  youtube_player_flutter: ^8.1.2
  http: ^1.2.1

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "pro"
  image_path: "assets/icons/pro.png"

flutter:
  fonts:
    - family: Tenada
      fonts:
        - asset: assets/fonts/Tenada.ttf
    - family: OneMobile
      fonts:
        - asset: assets/fonts/ONE Mobile Bold.ttf
  assets:
    - assets/
    - assets/internal/
    - assets/jin/
    - assets/kazuya/
    - assets/paul/
    - assets/claudio/
    - assets/bryan/
    - assets/hwoarang/
    - assets/king/
    - assets/feng/
    - assets/asuka/
    - assets/azucena/
    - assets/jack-8/
    - assets/jun/
    - assets/lars/
    - assets/law/
    - assets/leroy/
    - assets/lili/
    - assets/nina/
    - assets/raven/
    - assets/xiaoyu/
    - assets/alisa/
    - assets/devil jin/
    - assets/dragunov/
    - assets/lee/
    - assets/leo/
    - assets/kuma/
    - assets/steve/
    - assets/panda/
    - assets/reina/
    - assets/shaheen/
    - assets/victor/
    - assets/yoshimitsu/
    - assets/zafina/

  uses-material-design: true