name: tekken8_framedata
description: tk8 framedata.
publish_to: 'none'

version: 13.1.0+147

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  html: ^0.15.5
  math_expressions: ^2.6.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.1.2
  upgrader: ^11.3.1
  in_app_update: ^4.2.3
  shared_preferences: ^2.2.2
  string_validator: ^1.0.2
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_mobile_ads: ^5.2.0
  sticky_headers: ^0.3.0+2
  linked_scroll_controller: ^0.2.0
  youtube_player_flutter: ^9.1.1
  http: ^1.2.1
  firebase_core: ^3.2.0
  cloud_firestore: ^5.6.1
  firebase_analytics: ^11.4.0
  cached_network_image: ^3.4.0
  intl: ^0.19.0
  easy_localization: ^3.0.7


dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/pro.png"
  android: true
  image_path: "assets/icons/pro.png"

flutter:
  fonts:
    - family: Tenada
      fonts:
        - asset: assets/fonts/Tenada.ttf
    - family: OneMobile
      fonts:
        - asset: assets/fonts/ONE Mobile Bold.ttf
  assets:
    - assets/internal/patch_note.json
    - assets/json/
    - assets/icons/
    - assets/localizations/

  uses-material-design: true

dependency_overrides:
  webview_flutter_android: 4.3.0