// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'main.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        if(isPro){
          return android_vpro;
        }
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVsNmNWOf92n3fORCJMsVx7NF_MZ-Z6Dg',
    appId: '1:648481478664:web:d51debef5b9b43a26919bd',
    messagingSenderId: '648481478664',
    projectId: 'tk8-framedata-pro',
    authDomain: 'tk8-framedata-pro.firebaseapp.com',
    databaseURL: 'https://tk8-framedata-pro-default-rtdb.firebaseio.com',
    storageBucket: 'tk8-framedata-pro.appspot.com',
    measurementId: 'G-SJ6Y10EPFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwdg9HPq1EML2VPQT9eE2sI-8SNfkjBgo',
    appId: '1:648481478664:android:a4d357679f10a2e76919bd',
    messagingSenderId: '648481478664',
    projectId: 'tk8-framedata-pro',
    databaseURL: 'https://tk8-framedata-pro-default-rtdb.firebaseio.com',
    storageBucket: 'tk8-framedata-pro.appspot.com',
  );

  static const FirebaseOptions android_vpro = FirebaseOptions(
    apiKey: 'AIzaSyBwdg9HPq1EML2VPQT9eE2sI-8SNfkjBgo',
    appId: '1:648481478664:android:734e178062681bfb6919bd',
    messagingSenderId: '648481478664',
    projectId: 'tk8-framedata-pro',
    databaseURL: 'https://tk8-framedata-pro-default-rtdb.firebaseio.com',
    storageBucket: 'tk8-framedata-pro.appspot.com',
  );
}
